"""add_faculty_section_assignments

Revision ID: 20daf3eedfaf
Revises: b3c4d5e6f7a8
Create Date: 2026-05-19 13:23:09.745853

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20daf3eedfaf'
down_revision: Union[str, Sequence[str], None] = 'b3c4d5e6f7a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('faculty_section_assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('faculty_id', sa.Integer(), nullable=False),
    sa.Column('section_id', sa.Integer(), nullable=False),
    sa.Column('subject', sa.String(length=100), nullable=False),
    sa.Column('semester', sa.SmallInteger(), nullable=False),
    sa.Column('assigned_by_admin_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['assigned_by_admin_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['faculty_id'], ['faculty.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['section_id'], ['sections.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('faculty_id', 'section_id', 'subject', name='uq_faculty_section_subject')
    )
    op.create_index(op.f('ix_faculty_section_assignments_assigned_by_admin_id'), 'faculty_section_assignments', ['assigned_by_admin_id'], unique=False)
    op.create_index(op.f('ix_faculty_section_assignments_faculty_id'), 'faculty_section_assignments', ['faculty_id'], unique=False)
    op.create_index(op.f('ix_faculty_section_assignments_id'), 'faculty_section_assignments', ['id'], unique=False)
    op.create_index(op.f('ix_faculty_section_assignments_section_id'), 'faculty_section_assignments', ['section_id'], unique=False)
    op.create_index('ix_fsa_faculty_section', 'faculty_section_assignments', ['faculty_id', 'section_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_fsa_faculty_section', table_name='faculty_section_assignments')
    op.drop_index(op.f('ix_faculty_section_assignments_section_id'), table_name='faculty_section_assignments')
    op.drop_index(op.f('ix_faculty_section_assignments_id'), table_name='faculty_section_assignments')
    op.drop_index(op.f('ix_faculty_section_assignments_faculty_id'), table_name='faculty_section_assignments')
    op.drop_index(op.f('ix_faculty_section_assignments_assigned_by_admin_id'), table_name='faculty_section_assignments')
    op.drop_table('faculty_section_assignments')
    # ### end Alembic commands ###
